@startuml
left to right direction

class App {
  - {static} clock: Clock
  + App()
  + main(String[])
  + run(Scanner)
  + run(Scanner, boolean)
  + {static} now(): LocalDateTime
  -firstParse(String)
  -{static}echo(String[])
  -{static}help()
  -{static}parser(String)
  -{static}auxParser(String, String[])
  -{static}cutter(String[]): String[]
  -{static}printInvalidDataType(String, String, String)
  -{static}tryParseInt(String): Integer
  -{static}checkMaxArgsCountWithPrint(String, int, int): boolean
  -{static}checkMinArgsCountWithPrint(String, int, int): boolean
  -{static}checkArgsCountWithPrint(String, int, int, int): boolean
  -{static}checkArgsCountWithPrint(String, int, int): boolean
}

interface Command {
  + eval(String[])
}

class ClientCommand implements Command {
  - evalAdd(String[])
  - evalRemove(String[])
  - evalList()
}

class CashCommand implements Command {
  - evalAddCash(String[])
  - evalRemove(String[])
  - evalList(String[])
  - evalTickets(String[])
}

class TicketCommand implements Command {
  - evalNew(String[])
  - evalAdd(String[])
  - evalRemove(String[])
  - evalPrint(String[])
  - evalList(String[])
  - parsePersonalizations(int, String[]): String[]
}

class ProductCommand implements Command {
  - evalAdd(String[])
  - evalAddBase(String[])
  - evalAddTimed(String[])
  - evalAddService(String[])
  - evalUpdate(String[])
  - evalRemove(String[])
  - evalList(String[])
}

abstract class InventoryItem{
 - id: int

 + InventoryItem(int)
 + getId(): int
 + duplicateOf(InventoryItem): boolean
 + toString(): String
 + isValidId(int): boolean
}

class InventoryItemId{
 + id: int
 + isProduct: boolean

 + InventoryItemId(int, boolean)
}

abstract class Product extends InventoryItem{
  + {static} PRODUCT_MAX_NAME_LENGTH: int
  - name: String
  - price: double

  + Product(int, String, double):
  + getName(): String
  + getPrice(): Double
  + setName(String)
  + setPrice(Double)
  + {abstract} duplicateOf(Product): boolean
}

enum ServiceCategory{
 + TRANSPORT
 + SHOW
 + INSURANCE
}
class ServiceProduct extends InventoryItem{
 + {static} SERVICE_DISCOUNT: float
 + {static} EXPIRATION_DATE_FORMAT: DateTimeFormatter

 - expirationDate: LocalDateTime
 - category: ServiceCategory

 + ServiceProduct(int,ServiceCategory,LocalDateTime)
 + {static} newFromId(String, ServiceCategory, LocalDateTime): ServiceProduct
 + getCategory(): ServiceCategory
 + getExpirationDate(): LocalDateTime
}

enum Category {
  + CLOTHES	    0.07, true
  + MERCH	   	0.00, true
  + STATIONERY 	0.05, false
  + BOOK	   	0.10, false
  + ELECTRONICS	0.03, false

  + getDiscountPercent(): float
  + getMaxPersonalizations(): int
}

class BaseProduct extends Product {
  - category: Category
  - maxPersonalizations: int

  + BaseProduct(int, String, double, Category, int):
  + getCategory(): Category
  + setCategory(Category)
  + toString(): String
}

enum TimedType {
  + FOOD: 72
  + MEETING: 12
  - hoursForPreparing: int

  - TimedType(int)
  + getHoursForPreparing(): int
  + {static} fromLabel(String): TimedType
}

class TimedProduct extends Product {
  + {static} TIMED_PRODUCT_MAX_PEOPLE: int
  - type: TimedType
  - amount: int
  - participants: int
  - expirationDate: LocalDateTime

  + TimedProduct(int, String, double, int, TimedType, LocalDateTime)
  + getType(): TimedType
  + getAmount(): int
  + setAmount(int)
  + getMaxParticipants(): int
  + toString(): String
}

class Inventory {
  + {static} MAX_PRODUCTS
  - productAmount: int

  + {static} isValidId(int): boolean
  + {static} isValidName(String): boolean
  - isValidPrice(double): boolean

  + createBaseProduct(int, String, Category, double, int): BaseProduct
  + createTimedProduct(): TimedProduct
  + readProductIndex(int): int
  + readProduct(int): Product
  + updateProductName(int, String): Product
  + updateProductPrice(int, double): Product
  + updateProductCategory(int, Category): BaseProduct
  + deleteProduct(int): boolean

  + listProducts(): Product[]
  + generateUniqueProductId(): int
}

abstract class Ticket {
  + {static} MAX_PRODUCTS: int
  + {static} PERSONALIZATION_EXTRA_PERCENT: float
  + {static} ID_DATE_FORMAT: SimpleDateFormat
  + {static} DECIMAL_FORMAT: DecimalFormat

  - totalAmount: int
  - id: int
  - composedId: String
  - dateOpened: Date
  - dateClosed: Date
  - isOpen: boolean

  + Ticket(int, boolean)
  + getDateClosed(): Date
  + getComposedId(): String
  + isOpen(): boolean
  + isEmpty(): boolean
  + close()
  + {abstract} validateItemKind(InventoryItem): boolean
  + {abstract} summaryString(): String

  + addItem(InventoryItem, int, String[])
  + removeItem(int)
  - findDuplicateItem(TicketItem): TicketItem
}

class ProductTicket extends Ticket{
  + ProductTicket(int, boolean)
  - categoriesProductCount(): int[]
}

class ServiceTicket extends Ticket{
  + ServiceTicket(int, boolean)
}

class CombinedTicket extends Ticket{
  + CombinedTicket(int, boolean)
  - categoriesProductCount(): int[]
}

abstract class TicketItem{
  - item: InventoryItem
  - amount: int

  + TicketItem(InventoryItem, int)
  + getItem(): InventoryItem
  + getAmount(): int
  + addAmount(int)
  + equals(TicketItem): boolean
  + getItemDiscount(): double
  + getDiscountPercentOverall(): double

  + {abstract} validate()
  + {abstract} toString(): String
  + {abstract} getPrice(): double
  + {abstract} copy(): TicketItem
}

class BaseTicketItem extends TicketItem{
  + personalizations: String[]

  + BaseTicketItem(BaseProduct, int, String[])
  + compareTo(TicketItem): int
  + equals(TicketItem): boolean
}

class TimedTicketItem extends TicketItem{
  + peopleAmount: int

  + TimedTicketItem(TimedProduct, int)
  + compareTo(TicketItem): int
}

class ServiceTicketItem extends TicketItem{
  + ServiceTicketItem(ServiceProduct)
  + getDiscountPercentOverall(int[]): double
}

abstract class User {
  - id: String
  - name: String
  - email: String

  + User(String, String, String)
  + getId(): String
  + getName(): String
  + getEmail(): String
  + equals(Object): boolean
}

enum IdType{
 + DNI
 + NIF
}

class Client extends User{
 + {static} MOD23_LUT: String
 + {static} NIF_CONTROL_LETTERS: String
 + {static} NIF_NUMERIC_ONLY: String
 + {static} NIF_LETTER_ONLY: String
 + {static} NIF_EITHER: String
 + managedBy: Cashier
 + ticketIds: List<Integer>
 + idType: IdType

 + Client(String, String, String, Cashier)
 + addTicket(String)
 + getIdType(String): IdType
 - {static}isValidDni(String): boolean
 - {static}isValidNif(String): boolean
 - {static}computeNifControlDigit(String): int
 - {static}matchesNifControl(char,char,int,char): boolean
 - {static}normalize(String): String
 + compareTo(Client): int
 + toString(): String
}

class Cashier extends User{
  + {static} COMPANY_DOMAIN: String

  + Cashier(String, String, String)
  + createTicket(int): boolean
  + findTicket(int): Ticket
  + getTickets(): Ticket[]
  + getTicketsString(): String
  + getCreatedTicketAmount(): int

  + {static} isCompanyEmail(String): boolean
  + {static} isValidId(String): boolean
  + compareTo(Cashier): int
  + toString(): String
}

class UserManager {
  + {static} MIN_CASHIER_ID: int
  + {static} MAX_CASHIER_ID: int
  + {static} MIN_TICKET_ID: int
  + {static} MAX_TICKET_ID: int

  - nextCashierId: int
  - nextTicketId: int

  - UserManager()
  + addClient(String, String, String, Cashier): boolean
  + removeClient(String): boolean
  + findClient(String): Client
  + listClients(): Client[]
  + getClientAmount(): int

  + addCashier(String, String, String): boolean
  + addCashier(String, String): boolean
  + removeCashier(String): boolean
  + findCashier(String): Cashier
  + listCashiers(): String
  + listCashierTickets(String): String
  + listCashierTicketsArray(String): String
  + getCashierAmount(): int

  + getAllTickets(): List<Ticket>
  + isTicketIdUnique(int): boolean
  + getTicketAmount(): int
  + generateUniqueTicketId(): Integer
  + generateUniqueCashierId(): String
}

class Serialize{
  - dataStore: Map<String, Serializable>
  + put(String, Serializable)
  + get(String): Serializable
  + save(String)
  + load(String)
}

Inventory *--> InventoryItem
Inventory *--> InventoryItemId

App --> Inventory
ProductTicket o--> TicketItem
ServiceTicket o--> TicketItem
CombinedTicket o--> TicketItem
BaseTicketItem o--> BaseProduct
TimedTicketItem o--> TimedProduct
ServiceTicketItem o--> ServiceProduct

UserManager *--> User
UserManager ..> Client
UserManager ..> Cashier
UserManager ..> Ticket

Cashier *--> Ticket
Client o--> Ticket
Client --> Cashier

App --> UserManager
App --> Command



@enduml
